py_sources = [
    'dataclasses.py',
    '_geometry.py',
    'geometry.py',
    '__init__.py',
    'math.py',
    'mpi_test.py',
    'nexus.py',
    'sfx_find_peaks.py',
    'sfx_index.py',
    '_smalldata.py',
    'smalldata.py',
    'tasklets.py',
    'task.py',
    'test.py',
    'xtc.py',
]

py3.install_sources(
    py_sources,
    pure: false,
    subdir: 'lute/tasks',
)

subdir('algorithms')
subdir('util')