[build-system]
requires = ["numpy", "mypy", "meson-python", "pybind11", "meson>=1.10.1"]
build-backend = "mesonpy"

[project]
name = "lute"
description="LCLS Unified Task Executor."
requires-python = ">=3.8"
dynamic = ["version"]
dependencies = [
    "pyyaml",
    "pydantic==1.10",
    "numpy",
    "requests",
    "zmq",
    "jinja2",
]
authors = [
    { name = "psrel", email = "psrel@slac.stanford.edu" },
]
license = { text = "BSD-3-Clause" }
readme = "README.md"
urls = { Homepage = "https://github.com/slac-lcls/lute" }
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "License :: OSI Approved :: BSD License",
    "Operating System :: OS Independent",
]

[tool.meson-python.args]
# Need to do this.... I couldn't for the life of me figure out how to get meson
# meson-python and the CMake projects to work well together for installing the
# shared library...
install = ['--skip-subprojects', 'spdlog']

[tool.cibuildwheel]
# Build for everything except:
# pp* (PyPy)
# cp36-* (Python 3.6)
# cp37-* (Python 3.7)
# *-win32 and *-manylinux_i686 (32-bit builds)
skip = ["pp*", "cp36-*", "cp37-*", "*-win32", "*-manylinux_i686"]

# Setup tests for build CI - not working atm
# test-requires = "pytest"
# test-command = "pytest ./tests/unit"

[project.optional-dependencies]
mypy = ["mypy"]
docs = [
    "mkdocs",
    "mkdocstring",
    "mkdocstring-python",
    "mkdocs-click",
    "mkdocs-material",
    "mkdocs-material-extensions",
]
mpi = ["mpi4py"]
test = ["pytest"]

[project.scripts]
run_task = "run_task:main"
subprocess_task = "subprocess_task:main"
launch_airflow = "launch_scripts.launch_airflow:main"
launch_prefect = "launch_scripts.launch_prefect:main"
launch_slurm = "launch_scripts.launch_maestro:main"
submit_slurm = "launch_scripts.submit_slurm:main"
## *** NOTE: The following are in different packages in installed directories vs repo
## I.e. utilties -> lute_utilities
setup_lute = "lute_utilities.setup.setup_lute:main"
lute_help = "lute_utilities.help.task_parameters:main"
dbview = "lute_utilities.dbview.dbview:main"


[tool.setuptools.package-data]
config = [
    "*.yaml",
    "templates/*.*"
]

[tool.setuptools]
script-files = [
    "utilities/activate_installation",
    "launch_scripts/submit_launch_airflow.sh",
    "launch_scripts/submit_launch_prefect.sh",
    "launch_scripts/submit_launch_slurm.sh",
    # "launch_scripts/submit_slurm.sh",
]

[tool.black]
line-length = 88
target-version = ['py39']
include = '\.pyi?$'
extend-exclude = '''(
    .*.sh
    #| .*.another_extension
    | README
)'''

# mypy global options:


[tool.ruff]
# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
]

# Same as Black.
line-length = 88
indent-width = 4
include = [
    "lute/**/*.py",
    "launch_scripts/*.py",
    "utilties/**/*.py",
    "workflows/**/*.py",
]
target-version = "py39"

[tool.ruff.lint]
# Enable Pyflakes (`F`) and a subset of the pycodestyle (`E`)  codes by default.
# Unlike Flake8, Ruff doesn't enable pycodestyle warnings (`W`) or
# McCabe complexity (`C901`) by default.
select = ["E4", "E7", "E9", "F"]
ignore = []

# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[tool.ruff.format]
# Like Black, use double quotes for strings.
quote-style = "double"

# Like Black, indent with spaces, rather than tabs.
indent-style = "space"

# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false

# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"

# Enable auto-formatting of code examples in docstrings. Markdown,
# reStructuredText code/literal blocks and doctests are all supported.
#
# This is currently disabled by default, but it is planned for this
# to be opt-out in the future.
docstring-code-format = false

# Set the line length limit used when formatting code snippets in
# docstrings.
#
# This only has an effect when the `docstring-code-format` setting is
# enabled.
docstring-code-line-length = "dynamic"
