py_sources = [
    'base.py',
    'bayfai.py',
    'cheetah.py',
    'geometry.py',
    '__init__.py',
    'mpi_tests.py',
    'nexus.py',
    'sfx_find_peaks.py',
    'sfx_index.py',
    'sfx_merge.py',
    'sfx_solve.py',
    'smd.py',
    'tests.py',
    'validators.py',
    'xtc.py',
]

py3.install_sources(
    py_sources,
    pure: false,
    subdir: 'lute/io/models',
)
