%YAML 1.3
---
title: "Config to run Cheetah task"
experiment: "mfx100903824"
run: "27"
date: "2025/09/29"
lute_version: 0.1      # Do not be change unless need to force older version
task_timeout: 600
work_dir: "/sdf/scratch/users/d/dorlhiac"
...
---
RunCheetah:                       # All variables are given as strings
  exp: "{{ experiment }}"         # Experiment name
  run: "{{ run }}"                # Run number
  dir: "/some/path"               # Path to raw_directory
  executable: "/sdf/group/lcls/ds/tools/om/conda/ana-4.0.66-py311-miniom/bin/mpirun"
  n_processes: 3                  # Number of processes to launch
  om_executable: "/sdf/scratch/users/d/dorlhiac/work/om_rel/bin/om_monitor"
  om_config: "/sdf/scratch/users/d/dorlhiac/work/cheetah_tests/cheetah_config.yaml"
  lute_template_cfg:
    template_name: "cheetah_template.yaml"
    output_path: "/sdf/scratch/users/d/dorlhiac/work/cheetah_tests/cheetah_config.yaml"
  cheetah_subconfig:
    om:
      processing_layer: "CheetahProcessing"
    data_retrieval_layer:
      data_sources:
        timestamp:
          type: "TimestampPsana"
        event_id:
          type: "EventIdPsana"
        detector_data:
          psana_name: "epix10k2M"
          calibration: "true"
        detector_distance:
          type: "EpicsVariablePsana"
          psana_name: "detector_z"
          value: "DetectorDistanceValue"
    cheetah:
      processed_directory: "/sdf/data/lcls/ds/mfx/mfx100903824/results"
      processed_filename_prefix: "{{ experiment }}-{{ run }}"
      class_sums_filename_prefix: "{{ run }}"
    crystallography:
      geometry_file: "/sdf/data/lcls/ds/mfx/mfx100903824/scratch/dorlhiac/test.geom"
      responding_url: null
    peakfinder8_peak_detection:
      adc_threshold: 100.0
      minimum_snr: 5.0
      min_pixel_count: 1
      max_pixel_count: 30
      local_bg_radius: 4
      bad_pixel_map_filename: null
      min_res: 80
      max_res: 800
    compression:
      run_compression: True
      backend: "roibinsz"
      compression_parameters:
        compressor: "qoz"
        abs_error: 42
        bin_size: 2
        roi_window_size: 9
