{%- macro step_pydantic_model(data) %}
{%- for field, sub_fields in data.items() %}
{%- if sub_fields is mapping %}
{{ field }}:
{{- step_pydantic_model(sub_fields)|indent(loop.depth*2, True) }}
{%- else %}
{{ field }}: {{ sub_fields | tojson }}
{%- endif %}
{%- endfor %}
{%- endmacro -%}

{%- if data_retrieval_layer is defined and data_retrieval_layer %}
om:
{{- step_pydantic_model(om.dict()) | indent(2, True) }}
{% endif %}

{%- if data_retrieval_layer is defined and data_retrieval_layer %}
data_retrieval_layer:
{{- step_pydantic_model(data_retrieval_layer.dict()) | indent(2, True) }}
{% endif %}

{%- if cheetah is defined and cheetah %}
cheetah:
{{- step_pydantic_model(cheetah.dict()) | indent(2, True) }}
{% endif %}

{%- if crystallography is defined and crystallography %}
crystallography:
{{- step_pydantic_model(crystallography.dict()) | indent(2, True) }}
{% endif %}

{%- if peakfinder8_peak_detection is defined and peakfinder8_peak_detection %}
peakfinder8_peak_detection:
{{- step_pydantic_model(peakfinder8_peak_detection.dict()) | indent(2, True) }}
{% endif %}

{%- if compression is defined and compression %}
compression:
{{- step_pydantic_model(compression.dict()) | indent(2, True) }}
{% endif %}
