# Will change name once `psrel` PyPI account can be created
# name: Build wheels, create release, and publish to PyPI
name: Build wheels and create release
on:
  push:
    # Disable this for forks. Its expensive, and the PyPI portion will fail later
    #if: github.repository_owner == "slac-lcls"
    # For now, only build for release tags
    tags:
      - 'v*'
  #  branches:
  #    - main
  #pull_request:
  #  branches:
  #    - main

jobs:
  # Build binaries
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        # Add back Mac and Windows builds when maestro supports them
        # os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4

      # Cache pip (for speedup)
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # Cache ccache (for speedup)
      - name: Cache ccache
        uses: actions/cache@v4
        with:
          path: .ccache
          key: ${{ runner.os }}-ccache-${{ github.ref }}
          restore-keys: |
            ${{ runner.os }}-ccache-


      - name: Build wheels
        # Check pyproject.toml for supported versions and additional config
        uses: pypa/cibuildwheel@v2.22.0
        env:
          CIBW_AFTER_BUILD: "ccache -s"

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl

  # Build source distribution
  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11" # Shouldn't matter

      # Meson setup runs, so we still need these unfortunately (for subprojects)
      # The code will not actually be compiled for the sdist
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y cmake ninja-build

      - name: Build sdist
        run: |
          python -m pip install build
          python -m build --sdist

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-sdist
          path: dist/*.tar.gz

  # Create release, publish
  # Will change name once `psrel` PyPI account can be created
  # create_release_and_publish_to_pypi:
  create_release:
    needs: [build_wheels, build_sdist]
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write
      contents: write
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Gather build artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: cibw-*
          path: dist
          merge-multiple: true

      # Will enable once `psrel` PyPI account can be created
      # - name: Publish to PyPI
      #   uses: pypa/gh-action-pypi-publish@release/v1

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
          generate_release_notes: true
